spring:
  application:
    name: cinema
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.testcontainers: INFO
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
data:
  source:
    - test.xlsx
    - src/main/resources/
